"""add_channel_id_in_group_table

Revision ID: 054cca5b8685
Revises: 82964c26d221
Create Date: 2021-05-20 22:18:14.820213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054cca5b8685'
down_revision = '82964c26d221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('channel_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'group', 'channel', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'channel_id')
    # ### end Alembic commands ###
