"""create_roll_call_table

Revision ID: 240e4fd445df
Revises: f9d5ee503852
Create Date: 2021-05-12 21:26:00.730359

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "240e4fd445df"
down_revision = "f9d5ee503852"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roll_call",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roll_call")
    # ### end Alembic commands ###
