"""create_roll_call_late_responder_table

Revision ID: 6af8e26f27e1
Revises: 240e4fd445df
Create Date: 2021-05-12 21:33:05.125403

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6af8e26f27e1"
down_revision = "240e4fd445df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roll_call_late_responder",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("roll_call_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["roll_call_id"],
            ["roll_call.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("roll_call_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roll_call_late_responder")
    # ### end Alembic commands ###
