"""create_group_user_table

Revision ID: 82964c26d221
Revises: e7789ebd5fca
Create Date: 2021-05-20 22:08:54.031801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82964c26d221'
down_revision = 'e7789ebd5fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_user',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_user')
    # ### end Alembic commands ###
