"""add_name_column_to_channel_table

Revision ID: 870ae8671e71
Revises: 6af8e26f27e1
Create Date: 2021-05-18 12:59:24.180966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870ae8671e71'
down_revision = '6af8e26f27e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'name')
    # ### end Alembic commands ###
