"""add is_admin column to channel_user table

Revision ID: 896109adc784
Revises: 0459f6b53354
Create Date: 2021-04-25 11:38:09.572001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896109adc784'
down_revision = '0459f6b53354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_user', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_user', 'is_admin')
    # ### end Alembic commands ###
